apiVersion: v1
kind: ConfigMap
metadata:
  name: estore-config
data:
  NODE_ENV: "production"
  PORT: "5000"
  CLIENT_URL: "http://estore.local"
  ADMIN_URL: "http://estore.local"
  ADMIN_EMAIL: "admin@estore.com"
