apiVersion: v1
kind: Secret
metadata:
  name: estore-secrets
type: Opaque
data:
  # Base64 encoded values
  # password -> cGFzc3dvcmQ=
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
  # mongodb://admin:password@mongodb:27017/estore?authSource=admin
  MONGO_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGI6MjcwMTcvZXN0b3JlP2F1dGhTb3VyY2U9YWRtaW4=
  # dev_jwt_secret_key_123 -> ZGV2X2p3dF9zZWNyZXRfa2V5XzEyMw==
  JWT_SECRET: ZGV2X2p3dF9zZWNyZXRfa2V5XzEyMw==
  # sk_test_dummy -> c2tfdGVzdF9kdW1teQ==
  STRIPE_SECRET_KEY: c2tfdGVzdF9kdW1teQ==
  # test@test.com -> dGVzdEB0ZXN0LmNvbQ==
  EMAIL_USER: dGVzdEB0ZXN0LmNvbQ==
  # dummy -> ZHVtbXk=
  EMAIL_PASS: ZHVtbXk=
